### PR TITLE
Update for crash & small hack

### PR DESCRIPTION
**Pull request by enricoangelon**
Updated crash due to palette
Made a small hack to prevent player from falling underground

### CODE REVIEW

**Comment by Creeperface01** [comment]
Are these blockstates ones from nukkit?

**Comment by enricoangelon** [comment]
No they aren't, not sure if Nukkit changed block states format but latest are not working with Synapse,  i don't think is that important as plugin is made for pocketmine

**Comment by Creeperface01** [comment]
It is important since you can switch between nukkit and pocketmine servers and since we aren't able to update blockstates during the game it's required to have them equal on all the servers

**Comment by Creeperface01** [comment]
However the only thing you need to do is take ones from nukkit and replace the current

**Comment by enricoangelon** [comment]
Do not pull, i miss something

**Comment by enricoangelon** [comment]
Done! Now you can safely pull it :)

**Pull request merged**
